#############################################################################
# Makefile for building: Muster_Maker
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Muster_Maker.pro
# Template: app
# Command: D:\Qt-Self-Build\qtbase\bin\qmake.exe -o Makefile Muster_Maker.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\Qt-Self-Build\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Muster_Maker.pro D:\Qt-Self-Build\qtbase\mkspecs\win32-msvc2012\qmake.conf D:\Qt-Self-Build\qtbase\mkspecs\features\spec_pre.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\common\msvc-desktop.conf \
		D:\Qt-Self-Build\qtbase\mkspecs\qconfig.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcollision.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcollision_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dcollision.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcore.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcore_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dinput.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dinput_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dlogic.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dlogic_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquick.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquick_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquickrenderer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquickrenderer_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dquickrenderer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3drenderer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3drenderer_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3drenderer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axbase_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axcontainer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axcontainer_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axserver.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axserver_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_bluetooth.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_bluetooth_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_clucene_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_clucene_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_core.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_declarative_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_declarative.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_designer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_help.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_help.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_location.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_location_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_location.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_network.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_nfc.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_nfc_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_nfc.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_positioning.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_positioning_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_positioning.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qml.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qmltest_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quick.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quick_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quickparticles_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_script.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_script.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_sensors_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_serialport_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_svg.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_svg_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_uiplugin.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_webchannel.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_webchannel_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_websockets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_websockets_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_winextras.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_winextras_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_winextras.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_assimpsceneparser.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_dsengine.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_eglvideonode.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_gltfsceneparser.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qdds.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qdeclarativeview.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qicns.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qico.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qjp2.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qminimal.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmng.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qsvg.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qsvgicon.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtga.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtiff.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qwbmp.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qwebp.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qwindows.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_wmfengine.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_dumpcpp.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_dumpdoc.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_lconvert.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_lrelease.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_lupdate.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qcollectiongenerator.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qdoc.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qhelpgenerator.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qlalr.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qml.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qml1plugindump.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmlimportscanner.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmllint.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmlmin.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmlprofiler.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmltestrunner.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_syncqt.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_uic.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri \
		D:\Qt-Self-Build\qtbase\mkspecs\features\qt_functions.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\qt_config.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\win32\qt_config.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\win32-msvc2012\qmake.conf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\spec_post.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\exclusive_builds.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\default_pre.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\win32\default_pre.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\resolve_config.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\default_post.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\win32\rtti.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\c++11.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\precompile_header.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\warn_on.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\qt.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\resources.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\moc.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\win32\opengl.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\uic.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\win32\windows.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\testcase_targets.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\exceptions.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\yacc.prf \
		D:\Qt-Self-Build\qtbase\mkspecs\features\lex.prf \
		Muster_Maker.pro \
		D:/Qt-Self-Build/qtbase/lib/qtmain.prl \
		D:/Qt-Self-Build/qtbase/lib/Qt5Widgets.prl \
		D:/Qt-Self-Build/qtbase/lib/Qt5Gui.prl \
		D:/Qt-Self-Build/qtbase/lib/Qt5Sql.prl \
		D:/Qt-Self-Build/qtbase/lib/Qt5Core.prl \
		D:/Qt-Self-Build/qtbase/plugins/platforms/qwindows.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qdds.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qicns.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qico.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qjp2.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qmng.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qtga.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qtiff.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qwbmp.prl \
		D:/Qt-Self-Build/qtbase/plugins/imageformats/qwebp.prl \
		D:/Qt-Self-Build/qtbase/lib/libEGL.prl \
		D:/Qt-Self-Build/qtbase/lib/libGLESv2.prl
	$(QMAKE) -o Makefile Muster_Maker.pro
D:\Qt-Self-Build\qtbase\mkspecs\features\spec_pre.prf:
D:\Qt-Self-Build\qtbase\mkspecs\common\msvc-desktop.conf:
D:\Qt-Self-Build\qtbase\mkspecs\qconfig.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcollision.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcollision_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dcollision.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcore.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dcore_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dinput.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dinput_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dlogic.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dlogic_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquick.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquick_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquickrenderer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3dquickrenderer_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3dquickrenderer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3drenderer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_3drenderer_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_3drenderer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axbase_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axcontainer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axcontainer_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axserver.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_axserver_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_bluetooth.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_bluetooth_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_clucene_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_clucene_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_core.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_declarative_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_declarative.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_designer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_designer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_gui.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_help.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_help.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_location.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_location_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_location.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_network.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_nfc.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_nfc_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_positioning.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_positioning_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qml.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qml.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qmltest_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quick.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quick_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_quick.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quickparticles_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_script.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_script.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_sensors_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_serialport_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_sql.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_svg.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_svg_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_svg.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_uiplugin.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_webchannel.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_webchannel_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_websockets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_websockets_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_winextras.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_winextras_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_xml.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_assimpsceneparser.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_dsengine.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_eglvideonode.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_gltfsceneparser.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qdds.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qdeclarativeview.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qicns.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qico.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qjp2.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qmng.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qsvg.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qsvgicon.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtga.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtiff.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qwbmp.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qwebp.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_plugin_wmfengine.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_dumpcpp.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_dumpdoc.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_lconvert.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_lrelease.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_lupdate.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qcollectiongenerator.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qhelpgenerator.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qlalr.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qml.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qml1plugindump.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmlimportscanner.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmllint.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmlmin.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmlprofiler.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_qmltestrunner.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_syncqt.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_uic.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri:
D:\Qt-Self-Build\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri:
D:\Qt-Self-Build\qtbase\mkspecs\features\qt_functions.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\qt_config.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\win32\qt_config.prf:
D:\Qt-Self-Build\qtbase\mkspecs\win32-msvc2012\qmake.conf:
D:\Qt-Self-Build\qtbase\mkspecs\features\spec_post.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\exclusive_builds.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\default_pre.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\win32\default_pre.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\resolve_config.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\exclusive_builds_post.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\default_post.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\win32\rtti.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\c++11.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\precompile_header.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\warn_on.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\qt.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\resources.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\moc.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\win32\opengl.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\uic.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\win32\windows.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\testcase_targets.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\exceptions.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\yacc.prf:
D:\Qt-Self-Build\qtbase\mkspecs\features\lex.prf:
Muster_Maker.pro:
D:/Qt-Self-Build/qtbase/lib/qtmain.prl:
D:/Qt-Self-Build/qtbase/lib/Qt5Widgets.prl:
D:/Qt-Self-Build/qtbase/lib/Qt5Gui.prl:
D:/Qt-Self-Build/qtbase/lib/Qt5Sql.prl:
D:/Qt-Self-Build/qtbase/lib/Qt5Core.prl:
D:/Qt-Self-Build/qtbase/plugins/platforms/qwindows.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qdds.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qicns.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qico.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qjp2.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qmng.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qtga.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qtiff.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qwbmp.prl:
D:/Qt-Self-Build/qtbase/plugins/imageformats/qwebp.prl:
D:/Qt-Self-Build/qtbase/lib/libEGL.prl:
D:/Qt-Self-Build/qtbase/lib/libGLESv2.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Muster_Maker.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) "E:\My Documents\Qt Projects\Muster_Maker\muster_maker_plugin_import.cpp"

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
